services:
  - type: web
    name: tcrshows
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: TCRSHOWS_ADMIN_USER
        value: admin
      - key: TCRSHOWS_ADMIN_PASSWORD
        sync: false
      - key: TCRSHOWS_GITHUB_TOKEN
        sync: false
      - key: TCRSHOWS_GITHUB_REPO
        value: minfuzhang/tcrshows
      - key: TCRSHOWS_GITHUB_BRANCH
        value: main
